LLM:
  Dify:
    url: http://localhost/v1
    headerkey: app-uZdChxVBRe32nk5LvoMiqYSk
TTS:
  Doubao:
    appid: "4487078679"
    token: "HvLwi9jvzAOExH7hzbIxEndcZq3C28Dm"
    cluster: "volcano_tts"
    host: "openspeech.bytedance.com"
    url: "https://openspeech.bytedance.com/tts/v1/tts"
